name = "custom"
author = "akhlus"
variant = "dark"
opacity = "95"
base00 = "#1a1a2b" # base
base01 = "#161622" # mantle
base02 = "#32324d" # surface0
base03 = "#454569" # surface1
base04 = "#5c5c8d" # surface2
base05 = "#dadae7" # text
base06 = "#f5e0dc" # rosewater ##
base07 = "#b4befe" # lavender ##
base08 = "#ff5964" # red
base09 = "#f89777" # peach
base0A = "#f8d353" # yellow
base0B = "#06d6a0" # green
base0C = "#72e9c5" # teal ##
base0D = "#5ea0fc" # blue
base0E = "#9e72e9" # purple
base0F = "#a6e3a1" # lime
