# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "vmd" "nvme" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/66e4c953-cb1a-41c4-a972-4fc7fc7e3091";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5d915fed-d143-4502-8f9e-d11d33c3a5af".device = "/dev/disk/by-uuid/5d915fed-d143-4502-8f9e-d11d33c3a5af";
  boot.initrd.luks.devices."luks-ff0b491d-80f2-4264-9b6e-85dc74f2ad83".device = "/dev/disk/by-uuid/ff0b491d-80f2-4264-9b6e-85dc74f2ad83";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5D0D-D7D5";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/bf3fa086-66ef-4d84-a72c-08563b7ffd9f";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
