name = "alt_theme"
author = "Gemini"
variant = "dark"
opacity_ghostty = "0.95"
opacity_zed = ""
base00 = "#101010"       # base
base01 = "#181818"       # mantle
base02 = "#282828"       # surface0
base03 = "#383838"       # surface1
base04 = "#505050"       # surface2
base05 = "#e8e8e8"       # text
base06 = "#ff007f"       # rosewater ##
base07 = "#00ffff"       # lavender ##
base08 = "#ff5555"       # red
base09 = "#ff8700"       # peach
base0A = "#ffff55"       # yellow
base0B = "#50fa7b"       # green
base0C = "#4db6ac"       # teal ##
base0D = "#6272a4"       # blue
base0E = "#bd93f9"       # purple
base0F = "#c3e88d"       # lime
