name = "base16_theme"
author = "Gemini"
variant = "dark"
opacity_ghostty = "0.95"
opacity_zed = ""
base00 = "#101010"
base01 = "#202020"
base02 = "#303030"
base03 = "#505050"
base04 = "#B0B0B0"
base05 = "#D0D0D0"
base06 = "#E0E0E0"
base07 = "#F5F5F5"
base08 = "#F92672"
base09 = "#FD971F"
base0A = "#E6DB74"
base0B = "#A6E22E"
base0C = "#A1EFE4"
base0D = "#66D9EF"
base0E = "#AE81FF"
base0F = "#CC6633"
